
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GilG
 */
public class Almacen extends javax.swing.JFrame {

    Connection con=null;
    Statement stmt=null;
    ResultSet rs=null;
        
    public Almacen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonDescuento = new javax.swing.JButton();
        jButtonMostrar = new javax.swing.JButton();
        jSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 347));

        jButtonDescuento.setText("Descontar");
        jButtonDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDescuentoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        jSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jSpinner.setToolTipText("1");
        jSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 50, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 750, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        
       
        
     try {
 //Para establecer el modelo al JTable
         DefaultTableModel modelo = new DefaultTableModel();
         this.jTable.setModel(modelo);
 //Para conectarnos a nuestra base de datos
         DriverManager.registerDriver(new com.mysql.jdbc.Driver());
         con = DriverManager.getConnection("jdbc:mysql://localhost/hospital", "root", "");
 
 //Ejecutamos la consulta que escribimos en la caja de texto
 //y los datos lo almacenamos en un ResultSet
 stmt=con.createStatement();
            rs=stmt.executeQuery("select * from Medicamentos");
          
 //Obteniendo la informacion de las columnas que estan siendo consultadas
 ResultSetMetaData rsMd = rs.getMetaData();
 //La cantidad de columnas que tiene la consulta
 int cantidadColumnas = rsMd.getColumnCount();
 //Establecer como cabezeras el nombre de las colimnas
 for (int i = 1; i <= cantidadColumnas; i++) {
  modelo.addColumn(rsMd.getColumnLabel(i));
 }
 //Creando las filas para el JTable
 while (rs.next()) {
  Object[] fila = new Object[cantidadColumnas];
  for (int i = 0; i < cantidadColumnas; i++) {
    fila[i]=rs.getObject(i+1);
  }
  modelo.addRow(fila);
 }
 rs.close();
 con.close();
} catch (Exception ex) {
 ex.printStackTrace();
}
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void jButtonDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDescuentoActionPerformed
                
       
       try{         
           int selectfila = jTable.getSelectedRow();
        
          if(selectfila >=0){
              
              int des = (int)jTable.getValueAt(selectfila,3);
              int co = (int)jTable.getValueAt(selectfila,0);
              int nu =(int)(jSpinner.getValue());
              int res=0,disp=0;
              
              //Driver para conectarnos ala BD
             DriverManager.registerDriver(new com.mysql.jdbc.Driver());
             con = DriverManager.getConnection("jdbc:mysql://localhost/hospital", "root", "");
             
             stmt=con.createStatement();             
                   rs=stmt.executeQuery("select disponibles from Medicamentos where cod_medi='"+co+"'");
                   while (rs.next()) {
                    disp=rs.getInt("disponibles");
  }
                   System.out.println(disp);
             if(disp>nu){
           
             stmt=con.createStatement();             
             
                res = des - nu;
                  stmt.executeUpdate("UPDATE Medicamentos SET disponibles =('"+res+"') where cod_medi = '"+co+"' ");
                    
                System.out.println(res);
          }else{
                    JOptionPane.showOptionDialog(this, "No hay sudficientes medicinas", "Precaucion", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" OK "},"OK");
          
          }
          }else{
             JOptionPane.showOptionDialog(this, "Seleccione una Medicina", "Precaucion", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{" OK "},"OK");
          }
         
       }catch (Exception ex) {
         ex.printStackTrace();
             
        }  try {
 //Para establecer el modelo al JTable
         DefaultTableModel modelo = new DefaultTableModel();
         this.jTable.setModel(modelo);
 //Para conectarnos a nuestra base de datos
         DriverManager.registerDriver(new com.mysql.jdbc.Driver());
         con = DriverManager.getConnection("jdbc:mysql://localhost/hospital", "root", "");
 
 //Ejecutamos la consulta que escribimos en la caja de texto
 //y los datos lo almacenamos en un ResultSet
 stmt=con.createStatement();
            rs=stmt.executeQuery("select * from Medicamentos");
          
 //Obteniendo la informacion de las columnas que estan siendo consultadas
 ResultSetMetaData rsMd = rs.getMetaData();
 //La cantidad de columnas que tiene la consulta
 int cantidadColumnas = rsMd.getColumnCount();
 //Establecer como cabezeras el nombre de las colimnas
 for (int i = 1; i <= cantidadColumnas; i++) {
  modelo.addColumn(rsMd.getColumnLabel(i));
 }
 //Creando las filas para el JTable
 while (rs.next()) {
  Object[] fila = new Object[cantidadColumnas];
  for (int i = 0; i < cantidadColumnas; i++) {
    fila[i]=rs.getObject(i+1);
  }
  modelo.addRow(fila);
 }
 rs.close();
 con.close();
} catch (Exception ex) {
 ex.printStackTrace();
}
       
        
    }//GEN-LAST:event_jButtonDescuentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Almacen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDescuento;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
